Add documentation, light refactor, and more tests
Signed-off-by: bytemare <3641580+bytemare@users.noreply.github.com>

diff --git a/.github/Makefile b/.github/Makefile
--- a/.github/Makefile
+++ b/.github/Makefile
@@ -12,8 +12,8 @@ update-linters:
 	@go install github.com/segmentio/golines@latest
 	@go install github.com/google/addlicense@latest
 	@go install golang.org/x/tools/cmd/goimports@latest
+	@go install golang.org/x/vuln/cmd/govulncheck@latest
 	@go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
-	@curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
 
 .PHONY: fmt
 fmt:
@@ -36,12 +36,49 @@ lint: fmt license
 	@if golangci-lint config verify -v --config=.golangci.yml; then echo "Config OK"; else return 1; fi;
 	@if golangci-lint run --config=.golangci.yml ../...; then echo "Linting OK"; else return 1; fi;
 
+.PHONY: vulncheck
+vulncheck:
+	@echo "Running govulncheck ..."
+	@govulncheck -show verbose ../...
+
 .PHONY: test
 test:
 	@echo "Running all tests ..."
 	@go test -v -vet=all ../...
 
+.PHONY: vectors
+vectors:
+	@echo "Testing vectors ..."
+	@go test -v ../tests/vectors_test.go
+
 .PHONY: cover
 cover:
 	@echo "Testing with coverage ..."
 	@go test -v -race -covermode=atomic -coverpkg=../... -coverprofile=./coverage.out ../tests
+
+.PHONY: fuzz
+fuzz:
+	@echo "Running fuzz tests ..."
+	@fuzzTime=$${FUZZTIME:-2}; \
+    failed=0; \
+    find .. -name '*_test.go' -exec grep -l '^func Fuzz' {} \; | while read -r file; do \
+    	grep '^func Fuzz' "$$file" | sed -E 's/^func ([^(]+).*/\1/' | while read -r func; do \
+    		echo "Fuzzing $$func in $$file"; \
+    		if ! go test "$$(dirname "$$file")" -run="$$func" -fuzz="$$func" -fuzztime="$${fuzzTime}s"; then \
+    			failed=1; \
+    			echo "Crasher found for $$func. Crashing input:"; \
+    			testdata_dir="$$(dirname "$$file")/testdata/fuzz/$$func"; \
+    			if [ -d "$$testdata_dir" ]; then \
+    				latest_crasher=$$(ls -t "$$testdata_dir" | head -n 1); \
+    				if [ -n "$$latest_crasher" ]; then \
+    					cat "$$testdata_dir/$$latest_crasher"; \
+    				else \
+    					echo "Could not find crasher file in $$testdata_dir"; \
+    				fi; \
+    			else \
+    				echo "Could not find testdata directory: $$testdata_dir"; \
+    			fi; \
+    		fi; \
+    	done; \
+    done; \
+    exit $$failed
